name: commands
on:
  issue_comment:
    types: [created]

jobs:
  rustfmt:
    if: >
      github.event.comment.body == '@teto-bot rustfmt'
        && github.event.issue.pull_request
        && (github.event.comment.author_association == 'OWNER'
          || github.event.comment.author_association == 'COLLABORATOR'
          || github.event.comment.user.id == github.event.issue.user.id)
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge command with reaction
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            github.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: '+1'
            })

      - id: comment-branch
        uses: xt0rted/pull-request-comment-branch@v1
        with:
          repo_token: ${{ secrets.GH_PAT }}

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          default: true

      - run: cargo fmt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ steps.comment-branch.outputs.head_ref }}
          commit_message: Apply rustfmt
          commit_user_name: teto-bot
          commit_user_email: teto-bot@users.noreply.github.com
